### ISSUE TITLE
Unreported exception thrown

### ISSUE THREAD

**Issue by T14D3** [nea89o/Firmament#22]
Game crashes on "vanilla" (Fabric API, Fabric Language Kotlin, Firmament) Fabric 1.20.4 install when joining hypixel with the following error

```[12:26:04] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'net.minecraft.class_2487 net.minecraft.class_2507.method_10629(java.io.InputStream)'
	at moe.nea.firmament.features.inventory.storageoverlay.VirtualInventory$Serializer.deserialize(VirtualInventory.kt:44) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.VirtualInventory$Serializer.deserialize(VirtualInventory.kt:37) ~[Firmament-1.2.0.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.6.2-f395c4e1c18f8907.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeNullableSerializableElement(AbstractDecoder.kt:78) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageData$StorageInventory$$serializer.deserialize(StorageData.kt:19) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageData$StorageInventory$$serializer.deserialize(StorageData.kt:19) ~[Firmament-1.2.0.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.6.2-f395c4e1c18f8907.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.6.2-f395c4e1c18f8907.jar:?]
	at kotlinx.serialization.encoding.CompositeDecoder$DefaultImpls.decodeSerializableElement$default(Decoding.kt:538) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:111) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.internal.MapLikeSerializer.readElement(CollectionSerializers.kt:84) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.readElement$default(CollectionSerializers.kt:51) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.merge(CollectionSerializers.kt:36) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.internal.AbstractCollectionSerializer.deserialize(CollectionSerializers.kt:43) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at moe.nea.firmament.util.SortedMapSerializer.deserialize(SortedMapSerializer.kt:23) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.util.SortedMapSerializer.deserialize(SortedMapSerializer.kt:16) ~[Firmament-1.2.0.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.6.2-f395c4e1c18f8907.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableValue(AbstractDecoder.kt:43) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.encoding.AbstractDecoder.decodeSerializableElement(AbstractDecoder.kt:70) ~[org_jetbrains_kotlinx_kotlinx-see-jvm-1.6.2-d5203682a92600d9.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableElement(StreamingJsonDecoder.kt:168) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.6.2-f395c4e1c18f8907.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageData$$serializer.deserialize(StorageData.kt:15) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageData$$serializer.deserialize(StorageData.kt:15) ~[Firmament-1.2.0.jar:?]
	at kotlinx.serialization.json.internal.StreamingJsonDecoder.decodeSerializableValue(StreamingJsonDecoder.kt:69) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.6.2-f395c4e1c18f8907.jar:?]
	at kotlinx.serialization.json.Json.decodeFromString(Json.kt:107) ~[org_jetbrains_kotlinx_kotlinx-sen-jvm-1.6.2-f395c4e1c18f8907.jar:?]
	at moe.nea.firmament.util.data.ProfileSpecificDataHolder.readValues(ProfileSpecificDataHolder.kt:53) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.util.data.ProfileSpecificDataHolder.<init>(ProfileSpecificDataHolder.kt:37) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageOverlay$Data.<init>(StorageOverlay.kt:20) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageOverlay$Data.<clinit>(StorageOverlay.kt) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageOverlay.rememberContent(StorageOverlay.kt:55) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageOverlay.access$rememberContent(StorageOverlay.kt:17) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageOverlay$onLoad$2.invoke(StorageOverlay.kt:49) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.features.inventory.storageoverlay.StorageOverlay$onLoad$2.invoke(StorageOverlay.kt:48) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.events.FirmamentEventBus.publish(FirmamentEventBus.kt:34) ~[Firmament-1.2.0.jar:?]
	at moe.nea.firmament.Firmament.onClientInitialize$lambda$2(Firmament.kt:128) ~[Firmament-1.2.0.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.3+78d798af4f-60d2bffc28d75ec1.jar:?]
	at net.minecraft.class_310.handler$zen000$fabric-lifecycle-events-v1$onEndTick(class_310.java:4277) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2067) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[minecraft-1.20.4-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:578) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) ~[NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) ~[NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) ~[NewLaunch.jar:?]```

**Comment by nea89o** [comment]
Yep! 1.20.4 does have some bugs still. I will have a dedicated 1.20.4 release out probably today.

**Comment by T14D3** [comment]
Great, no rush, just wanted to let you know^^

**Comment by nea89o** [comment]
> Great, no rush, just wanted to let you know^^

Nope, yes rush, lol! I've been working on this for about 2 days or so, since dulkir is now also on 1.20.4: https://modrinth.com/mod/firmament/version/w3Ub8fMS
