### ISSUE TITLE
Custom textures crashes in event handler with cacheDuration = 0

### ISSUE THREAD

**Issue by AenderErSeje** [nea89o/Firmament#24]
[19:55:21] [Render thread/ERROR]: Caught exception during processing event TickEvent(tickCount=1923) by Handler(invocation=(moe.nea.firmament.events.TickEvent) -> kotlin.Unit, receivesCancelled=false)
java.lang.ArithmeticException: / by zero
	at moe.nea.firmament.features.texturepack.CustomSkyBlockTextures$onLoad$2.invoke(CustomSkyBlockTextures.kt:47) ~[Firmament-1.3.2.jar:?]
	at moe.nea.firmament.features.texturepack.CustomSkyBlockTextures$onLoad$2.invoke(CustomSkyBlockTextures.kt:46) ~[Firmament-1.3.2.jar:?]
	at moe.nea.firmament.events.FirmamentEventBus.publish(FirmamentEventBus.kt:34) ~[Firmament-1.3.2.jar:?]
	at moe.nea.firmament.Firmament.onClientInitialize$lambda$2(Firmament.kt:128) ~[Firmament-1.3.2.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.3.0+a67ffb5d4f-509da73f0c38ec40.jar:?]
	at net.minecraft.class_310.handler$zlp000$fabric-lifecycle-events-v1$onEndTick(class_310.java:6277) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2067) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1289) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.6-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]

[23:59:59] [Render thread/ERROR]: Caught exception during processing event TickEvent(tickCount=295039) by Handler(invocation=(moe.nea.firmament.events.TickEvent) -> kotlin.Unit, receivesCancelled=false)
java.lang.ArithmeticException: null

**Comment by nea89o** [comment]
Yep ill fix that. For the time being you can just turn the cache duration up to 1 for the custom models.
